---
- name: Install MySQL, Redis, and Docker Swarm on EC2
  hosts: ec2_instance
  become: yes
  
  pre_tasks:
    - name: Update package cache (Amazon Linux)
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"
      
    - name: Update package cache (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - mysql
    - redis  
    - docker